import { StyleSheet, Platform } from 'react-native';

export const globalStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  row: { flexDirection: 'row', alignItems: 'center' },
  topBar: { position: 'absolute', top: 0, left: 0, right: 0, height: 90, paddingTop: 40, paddingHorizontal: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', zIndex: 100 },
  topBtn: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  progressWrapper: { flex: 1, marginHorizontal: 20, height: 4, backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 2, overflow: 'hidden' },
  progressTrack: { flex: 1 },
  progressFill: { height: '100%', backgroundColor: '#0A84FF' },
  bottomBar: { position: 'absolute', bottom: 30, left: 20, right: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', zIndex: 100 },
  roundGlassBtn: { width: 56, height: 56, borderRadius: 28, backgroundColor: 'rgba(10, 132, 255, 0.2)', borderWidth: 1, borderColor: 'rgba(10, 132, 255, 0.5)', justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
  playBtn: { width: 70, height: 70, borderRadius: 35, backgroundColor: '#0A84FF', justifyContent: 'center', alignItems: 'center', shadowColor: '#0A84FF', shadowOpacity: 0.5, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 5 },
  glassCard: { padding: 20, borderRadius: 24, marginBottom: 16, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  card: { backgroundColor: '#1C1C1E', padding: 20, borderRadius: 24, marginBottom: 16 },
  sectionHeader: { fontSize: 13, fontWeight: 'bold', color: '#0A84FF', marginLeft: 8, marginBottom: 8, textTransform: 'uppercase', letterSpacing: 1, marginTop: 10 },
  label: { fontSize: 11, fontWeight: '700', color: '#888', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 1 },
  glassInput: { backgroundColor: 'rgba(0,0,0,0.4)', color: '#fff', padding: 14, borderRadius: 12, fontSize: 15, marginBottom: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  slider: { width: '100%', height: 40, marginTop: 4, marginBottom: 12 },
  seedRow: { flexDirection: 'row', alignItems: 'center' },
  iconBtn: { backgroundColor: 'rgba(0,0,0,0.4)', width: 48, height: 48, borderRadius: 12, marginLeft: 8, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  iconBtnActive: { backgroundColor: '#0A84FF', borderColor: '#0A84FF' },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  segmentedControl: { flexDirection: 'row', backgroundColor: '#333', padding: 4, borderRadius: 14, flex: 1, marginRight: 15 },
  segment: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 10 },
  segmentActive: { backgroundColor: '#555' },
  segmentText: { color: '#888', fontSize: 14, fontWeight: '600' },
  segmentTextActive: { color: '#fff' },
  wfCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1C1C1E', padding: 16, borderRadius: 16, marginBottom: 12, borderWidth: 1, borderColor: '#333' },
  wfCardActive: { borderColor: '#0A84FF' },
  wfCardTitle: { fontSize: 17, fontWeight: '600', color: '#fff', marginBottom: 4 },
  wfCardSub: { fontSize: 13, color: '#888' },
  primaryBtn: { backgroundColor: '#0A84FF', padding: 16, borderRadius: 16, alignItems: 'center' },
  primaryBtnText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  modalScroll: { padding: 20, paddingTop: 60, paddingBottom: 100 },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', alignItems: 'center' },
  popup: { width: '90%', backgroundColor: '#1C1C1E', padding: 24, borderRadius: 24, borderWidth: 1, borderColor: '#333' },
  title: { fontSize: 28, fontWeight: 'bold', color: '#fff' },
  rowItemClear: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  emptyText: { textAlign: 'center', color: '#666', fontSize: 16, padding: 20 },
  toast: { position: 'absolute', bottom: 120, alignSelf: 'center', backgroundColor: 'rgba(0,0,0,0.8)', paddingVertical: 12, paddingHorizontal: 24, borderRadius: 20, zIndex: 999, borderWidth: 1, borderColor: '#333' },
  toastText: { color: '#fff', fontSize: 15, fontWeight: 'bold' },
  tutorialText: { color: '#ccc', fontSize: 16, lineHeight: 24, marginBottom: 15 }
});